### ISSUE TITLE
Please add to NL translation

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#1]
msgctxt "#40355"
msgid "Optional icons and fanart packs"
msgstr "Optionele icon en fanart verzameling"

msgctxt "#40356"
msgid "Reboot from NAND (Android)"
msgstr "Herstart vanaf NAND (Android)"

**Comment by b-jesch** [comment]
This has be done, but this needs translation too:

msgctxt "#40353"
msgid "Use poster view for music video widgets"
msgstr ""

msgctxt "#40354"
msgid "Show year of publication in title"
msgstr ""

**Comment by freaktabnl** [comment]
msgctxt "#40353"
msgid "Use poster view for music video widgets"
msgstr "Gebruik posters voor muziek video widgets"

msgctxt "#40354"
msgid "Show year of publication in title"
msgstr "Laat jaar van publicatie zien in titel"

**Comment by b-jesch** [comment]
Done. Thank You for contribution!

**Comment by freaktabnl** [comment]
> Done. Thank You for contribution!

My name on Kodi forum is theghostnl ;)
