### ISSUE TITLE
PVR artwork module

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#10]
First install **PVR artwork module** and then update, otherwise you get a error (dependency not met)

![image](https://user-images.githubusercontent.com/36622939/126970157-42295094-47c8-497c-84aa-6164bd874778.png)

**Comment by freaktabnl** [comment]
https://repo.kodinerds.net/index.php?action=list&scope=last

**Comment by b-jesch** [comment]
If you update the skin from Nerdsrepo this should be done automatically in normal cases. Dependency to the module is listed in the addon.xml: https://github.com/b-jesch/skin.estuary.modv2/blob/f7de4cd5961dba1c037edd33e95cb2855e750621/addon.xml#L10

**Comment by b-jesch** [comment]
May I close this issue?
