### ISSUE TITLE
Flickering of Background While Zattoo PVR Is Running

### ISSUE THREAD

**Issue by hawkeyexp** [b-jesch/skin.estuary.modv2#102]
Hi, it is no new bug but i think it should be addressed:

i'm using zattoo pvr plugin for live tv - if a channel is selected and playing and you leave full screen to get the channel list or entering an other menu etc. the background starts fast flickering - it feels like a refresh bug and the systems get's a bit laggy. Log contains no errors - i'm open to support finding the prob but let me know what is helpfull to identify.

**Comment by b-jesch** [comment]
Is the same behaviour present on default Estuary?

**Comment by hawkeyexp** [comment]
No only with the mod.
Setup is custom background image and vid visible in background.

**Comment by b-jesch** [comment]
Since I am not able to reproduce this effect (I use IPTVSimple, HTS TVHeadend as clients), I opened a thread on the German community Kodinerds. Let's see there further: https://www.kodinerds.net/index.php/Thread/76346-Estuary-Mod-V2-Zattoo-PVR-Plugin-Video-flackert-wenn-dieses-im-Hintergrund-l%C3%A4uft/

**Comment by NelvinBHV** [comment]
I had the same problem. I think you are running LibreELEC on a Pi4. You have so change under Settings -> Player the PRIME-Rendering to EGL. No flickering anymore. I hope it helps

**Comment by rainman74** [comment]
no problem here on Windows and Android with Zattoo PVR.

**Comment by b-jesch** [comment]
@hawkeyexp: Any news?

**Comment by b-jesch** [comment]
Closed due no response from opener.
