### ISSUE TITLE
PVR

### ISSUE THREAD

**Issue by quickmic** [b-jesch/skin.estuary.modv2#104]
Hi
Kodi (19.4) crashes when playing PVR content. Actually I tracked it down to the Custom_1134_PVRNextUp.xml file.

There are two crashes:

First crash appears if you trigger pvr playback (tested via simple IP tv) AND open the status bar.

This is related to those lines:

```
<visible>Window.IsActive(fullscreenvideo) + VideoPlayer.Content(livetv) + !Skin.HasSetting(disable_PVRNextUp)</visible>
<visible>!Window.IsVisible(VideoOSD.xml) + !Window.IsVisible(DialogPVRChannelsOSD.xml) + !Window.IsVisible(DialogPVRChannelGuide.xml) + !Window.IsVisible(DialogFullScreenInfo.xml) + !Window.IsVisible(Custom_1135_PVROverlay.xml)</visible>
```

imho it makes no sense to set the visibility twice. They will overwrite each other, so I combined them, but still Kodi crashed.
The fix was removing "!Window.IsVisible(VideoOSD.xml)" parameter:
```
<visible>Window.IsActive(fullscreenvideo) + VideoPlayer.Content(livetv) + !Skin.HasSetting(disable_PVRNextUp) + !Window.IsVisible(DialogPVRChannelsOSD.xml) + !Window.IsVisible(DialogPVRChannelGuide.xml) + !Window.IsVisible(DialogFullScreenInfo.xml) + !Window.IsVisible(Custom_1135_PVROverlay.xml)</visible>
```

This solved the first crash, BUT there is another one when playback was stopped.
The only workaround I found here was removing both load triggers:

```
<onload>RunScript(script.module.pvr.artwork,get_artwork,prefix=PVR.Nextup&amp;title=$INFO[VideoPlayer.NextTitle]&amp;genre=$INFO[VideoPlayer.NextGenre]&amp;channel=$INFO[VideoPlayer.ChannelName])</onload>
<onunload>RunScript(script.module.pvr.artwork,clear_artwork,prefix=PVR.Nextup)</onunload>
```

After that PVR playback was stable. This needs further review, but I recommend apply my patches until the actual cause is found.
With the current version, PVR is unusable.

kind regards,
Michael

**Comment by b-jesch** [comment]
`Window.IsActive(fullscreeninfo)` and `!Window.IsVisible(DialogFullScreenInfo.xml)` are indeed competing, since they address the same window. I think that should be fixed and the two visible conditions should be put together. The visiblility of VideoOSD is a single condition that not should kodi crash.

there may be more race conditions that cause kodi to crash. This would have to be investigated. Btw I have not observed any crashes in connection with the NextUp window. I'm using TVHeadend.

> With the current version, PVR is unusable.

Simply disable the "Activate PVR Next Up Popup for Live TV" in skin settings.

**Comment by b-jesch** [comment]
> The only workaround I found here was removing both load triggers:
`<onload>RunScript(script.module.pvr.artwork,get_artwork,prefix=PVR.Nextup&amp;title=$INFO[VideoPlayer.NextTitle]&amp;genre=$INFO[VideoPlayer.NextGenre]&amp;channel=$INFO[VideoPlayer.ChannelName])</onload>
<onunload>RunScript(script.module.pvr.artwork,clear_artwork,prefix=PVR.Nextup)</onunload>`

Is the 'PVR Artwork Module' installed? Maybe there is a load/unload condition missing?

**Comment by b-jesch** [comment]
Could You check the last commit: https://github.com/b-jesch/skin.estuary.modv2/commit/f7c71189f9a67528c7e1a7a9ec8c98e0ddf467d4

Regards

**Comment by quickmic** [comment]
> 

Thanks and yes, sure. I keep you updated.

**Comment by quickmic** [comment]
After quick check, the commit seems to fix the issues. Great work and thanks  for the fast turnaround.

If the crashes re-appears, I'll upload a debug log. For the moment I close this report.

**Comment by b-jesch** [comment]
Thank you for contribution. You're welcome.
