### ISSUE TITLE
Feature request: implement embuary TV Guide

### ISSUE THREAD

**Issue by Mahava** [b-jesch/skin.estuary.modv2#105]
Hi,
Can you implement the TV Guide in Embuary helper/info.  I think it needs its own custom window?  Im thinking of something along the lines of the TMDB Helper TV Guide window implemented in Arctic Horizon 2 skin.  That skin has an option to use either Trakt or Kodi library shows to populate its TV Guide window. It also has an option for vertical or horizontal views.

Thank you for keeping this amazing skin alive.

**Comment by b-jesch** [comment]
For tv shows I've already implemented widgets for next up and next aired based on the local libraries. I don't know what you mean by Embuary TV guide. Could you explain this a little bit more (maybe screenshots)?

**Comment by Mahava** [comment]
The documentation for Embuary Info here:  https://github.com/sualfred/script.embuary.info

![image](https://user-images.githubusercontent.com/32604452/211949486-d53e2201-9408-4127-a041-1495d6107314.png)

It has support for TV guide Sunday to Monday but there's no window to view it in a TV guide format, that is, in columns and rows with the days across the top.   Sort of like the addon TV Show Next Aired used to do.

As for the next up and next aired that you say is implemented, I think you mean skin helper service widgets?   Some of those widgets don't work for me... the airing today one... which is why I'm looking for an alternative.   TV Show Next Aired doesn't work either and since Embuary is already a dependency....

**Comment by b-jesch** [comment]
> As for the next up and next aired that you say is implemented, I think you mean skin helper service widgets? 

No, both are implementations of embuary helper. See here and look at the content path of the widgets (Line 241, 248, 255, 262): 
https://github.com/b-jesch/skin.estuary.modv2/blob/1ed49bfc233e5de3210893824c46172eda128551/xml/Home.xml#L240-L267

The screenshot here shows a next aired item (Equalizer) as a part of the next aired widget: https://github.com/b-jesch/skin.estuary.modv2/blob/master/resources/screenshots/screenshot_7.png

As my local TVShow database doesn't have much content there is not much to see ;)
