### ISSUE TITLE
3.1.0+matrix CE 19 rc2 - unable to update 

### ISSUE THREAD

**Issue by Muza1** [b-jesch/skin.estuary.modv2#11]
I use a x96max+ (S905x3) box with Coreelec 19_rc2 and when updating to version 3.1.0+matrix i get a blank screen and and after a while some placeholders but no response to commands in the end i had to cut the power to reboot and revert back to 3.0.9+matrix.

Thank you very much for the mod, works really well.

**Comment by b-jesch** [comment]
Install PVR Artwork Module first: https://github.com/b-jesch/skin.estuary.modv2/issues/10

Estuary Mod 3.1.0 works very well on a Tanix TX3 here (S905x3)

**Comment by Muza1** [comment]
Thanks is now updated, all works, but the clock is showing just the first two digits.

**Comment by b-jesch** [comment]
Do You use another font then the default font, i.e. arial based? Switch back to the default font (setup -> user interface -> font)

**Comment by Muza1** [comment]
I changed the font back now is showing all the numbers but not the AM/PM status just 2 dots, i tried on a pc and has the same problem with the skin default settings.

**Comment by b-jesch** [comment]
Are you able to change a file within the skin? If so, unpack the zip and copy the Includes.xml to .kodi/addons/skin.estuary.modv2/xml/includes.xml

[Includes.zip](https://github.com/b-jesch/skin.estuary.modv2/files/6890906/Includes.zip)
