### ISSUE TITLE
Insert in resource.language.nl_nl/strings.po

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#110]
#: /xml/SkinSettings.xml

msgctxt "#31622"
msgid "Disabled timers"
msgstr "Timers welke uit staan"

#: SkinSettings.xml

msgctxt "#31623"
msgid "Default Action on 'Timer' Widgets"
msgstr "Standaard actie bij 'Timer' Widgets "

msgctxt "#31624"
msgid "Show Timer Settings"
msgstr "Timer instellingen"

msgctxt "#31625"
msgid "Show Broadcast Information"
msgstr "Uitzend informatie"

msgctxt "#31627"
msgid "Video and Audio OSD"
msgstr "Video en audio OSD"

msgctxt "#31628"
msgid "OSD Artwork"
msgstr "OSD afbeeldingen"

msgctxt "#31630"
msgid "Use simple Seekbar on Chapter and Time Seeking"
msgstr "Gebruik simpele zoekactie bij hoofdstuk en op tijd zoeken"

msgctxt "#31631"
msgid "Action on 'last channel switch' OSD Button"
msgstr ""

msgctxt "#31632"
msgid "Switch to last Channel directly"
msgstr "Ga rechtstreeks naar kanaal wisseling"

msgctxt "#31633"
msgid "Show last five Channels"
msgstr "Laat 5 laatste kanalen zien"

msgctxt "#31634"
msgid "Last watched"
msgstr "Laatst bekeken"

#: DialogContextMenu.xml

msgctxt "#31635"
msgid "Play Trailer"
msgstr "Speel trailer af"

msgctxt "#31636"
msgid "Show 'Play Trailer' in Context Menu"
msgstr "Laat trailer afspelen zien binnen context menu"

#: Skinsettings.xml

msgctxt "#31637"
msgid "Show Lyrics"
msgstr "Teksten van liedjes laten zien"

msgctxt "#31638"
msgid "Minimized Options Menu"
msgstr "Minimaliseer opties menu"

msgctxt "#31639"
msgid "Default Action on 'PVR' Widgets"
msgstr "Standaard actie bij PVR widgets"

**Comment by b-jesch** [comment]
Inserted. Could you translate this too?


#: /xml/SkinSettings.xml

msgctxt "#31640"
msgid "Enable background for splash screen"
msgstr ""

msgctxt "#31641"
msgid "Prefer Album Fanart over Artist Fanart"
msgstr ""

**Comment by freaktabnl** [comment]
msgctxt "#31640"
msgid "Enable background for splash screen"
msgstr "Achtergrond activeren voor splash beeld"

msgctxt "#31641"
msgid "Prefer Album Fanart over Artist Fanart"
msgstr "Album fanart boven artiesten fanart kiezen"

**Comment by freaktabnl** [comment]
msgctxt "#31637"
msgid "Show Lyrics"
msgstr "Teksten van liedjes laten zien"

Typo.....this one is correct

**Comment by b-jesch** [comment]
Thank you. Closed.
