### ISSUE TITLE
HDRtype icons in Dialog Videoinfo Nexus

### ISSUE THREAD

**Issue by frodo19** [b-jesch/skin.estuary.modv2#111]
Hi, the hdrtype mediaflags not visible in Videoinfo dialog, in nexus.

This type of icons was there in matrix version.

in DialogFullScreenInfo.xml > visible
in DialogVideoInfo.xml> not visible

**Comment by b-jesch** [comment]
> in DialogFullScreenInfo.xml > visible
> in DialogVideoInfo.xml> not visible

It's exactly reversed, but fixed now

**Comment by frodo19** [comment]
Yes, I have reversed, sorry. 
But in my kodi  is not visible. 
I'm use the latest nexus version of the skin.

**Comment by b-jesch** [comment]
It's not in the repo nor in github yet.

**Comment by frodo19** [comment]
Ok, which xml.s need I download, and change?

**Comment by b-jesch** [comment]
I'll push the changes to github next 5 minutes ;)

**Comment by b-jesch** [comment]
Done...

**Comment by frodo19** [comment]
Nice job, thanks!
