### ISSUE TITLE
Subtitles Enabled/Disabled Dialogue Missing

### ISSUE THREAD

**Issue by mmanuxx** [b-jesch/skin.estuary.modv2#112]
Using v3.4.2+matrix.20 on Windows 11. It may have happened in a previous version but I noticed it in this version. As title describes, there's no confirmation dialogue once subtitles are toggled.

**Comment by b-jesch** [comment]
There was never a confirmation dialog on subtitle change/activation, only a notification dialog. This is shown on Matrix and Nexus (W10, Linux). Just tested.

Maybe you have activated "Hide notification popup during playback" (Skin settings - General)

**Comment by b-jesch** [comment]
@mmanuxx: New insights? Can I close the issue?

**Comment by mmanuxx** [comment]
You were correct. It was the "Hide notification popup during playback" option which I had enabled. I didn't know it would effect that popup. So yes, close and thanks for your work.

**Comment by b-jesch** [comment]
Thank you for answer.
