### ISSUE TITLE
In file view in the Content panel the filename cropped

### ISSUE THREAD

**Issue by frodo19** [b-jesch/skin.estuary.modv2#114]
In the movie file folders, when the filename too long, the Skin not display that correctly.
Just crop or shift the name of the file to left. List view and Shift view affected as well, but maybe other views too.
Kodi Nexus version, but the matrix too.

Thanks

![Névtelen](https://user-images.githubusercontent.com/1296125/219846032-ec3e8a13-3d4a-4e0b-928a-7dbe1e347567.png)
![Névtelen1](https://user-images.githubusercontent.com/1296125/219846035-cca68365-f9c4-4a35-96c6-c0db9c3dadd5.png)

**Comment by b-jesch** [comment]
This is a limitation of the used textbox control. If labels ar too long and don't have spaces inside, the control doesn't have any chance to break the label into two or more lines.

Changing the textbox control to label control and set wrapmultiline fixed this issue.

BTW Normally this view shouldn't appear on file view...

**Comment by frodo19** [comment]
Thanks, works fine :)
