### ISSUE TITLE
Add Fullscreen Wall

### ISSUE THREAD

**Issue by Sparda333** [b-jesch/skin.estuary.modv2#116]
Appreciate if you add fullscreen Wall view like on Aeon Nox Slvo.

**Comment by b-jesch** [comment]
There are already full wall views available:

- Mosaic view (horizontal)
- Mosaic view (vertikal)
- Wall view (Poster)
- Wall view (Fanart)

**Comment by Sparda333** [comment]
Yeah but I prefer it without gaps it's a cleaner look.

**Comment by b-jesch** [comment]
These gaps are not close enough? Sorry a similar view without/closer gaps will not be implemented.

![Bildschirmfoto von 2023-03-01 11-12-33](https://user-images.githubusercontent.com/10152384/222110374-4e3ffe6b-a84a-4f64-a154-a7c4b732e885.png)

**Comment by Sparda333** [comment]
AHH ok. Just tried the mosaic view it cuts part of the image but in the preview picture it's full posters.
