### ISSUE TITLE
Watched check after info update

### ISSUE THREAD

**Issue by albertinozz** [b-jesch/skin.estuary.modv2#119]
HI
When I update info on a movie or series that I've already watched, after updating the info the movie or series appears as unwatched.
Here's a video
https://www.dropbox.com/s/02nl8w314nyxsmp/kodi_watched_check.mov?dl=0

**Comment by b-jesch** [comment]
Yes, that's a normal behaviour and appears on stock Estuary too. If You feel this is a bug or an issue please open a ticket on kodi: https://github.com/xbmc/xbmc/issues
