### ISSUE TITLE
Extra NL translations

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#12]
msgctxt "#40361"
msgid "Show PVR related Artworks"
msgstr "Laat PVR gerelateerde content zien"

msgctxt "#40362"
msgid "PVR Artwork Configuration"
msgstr "PVR content configuratie "

msgctxt "#40363"
msgid "Show date"
msgstr "Datum laten zien"

msgctxt "#40364"
msgid "Top Bar"
msgstr "Bovenste regel"

msgctxt "#40365"
msgid "Bottom Bar"
msgstr "Onderste regel"

msgctxt "#40366"
msgid "Media"
msgstr "Media"

msgctxt "#40367"
msgid "Kodi/Distribution Logo"
msgstr "Kodi/Distributie logo"

msgctxt "#40368"
msgid "LibreELEC"
msgstr "LibreELEC"

msgctxt "#40369"
msgid "CoreELEC"
msgstr "CoreELEC"

msgctxt "#40370"
msgid "Show extended Power Menu"
msgstr "Laat uitgebreide power menu zien"

msgctxt "#40371"
msgid "Prefer Fanart in EPG preview window if available"
msgstr "Laat fanart in EPG voorvertoning zien indien beschikbaar"

**Comment by b-jesch** [comment]
Thank You for contribution. Changes will be available on next update.

Regards
