### ISSUE TITLE
"Close Video OSD..." setting ignored

### ISSUE THREAD

**Issue by gohamstergo** [b-jesch/skin.estuary.modv2#121]
Kodi 20
4.1.1+nexus.11

"Skin Settings > General > Close Video OSD automatically after" setting seems to be ignored and the Video OSD hides 5 seconds after seeking regardless.

Recently updated to your fork after having an old Kodi 18 version that has some bugs on Nexus. I used to be able to have the OSD hide immediately after seeking and it would be great to have that option back. Thanks!

**Comment by b-jesch** [comment]
Just tested. Works as expected.

**Comment by gohamstergo** [comment]
k
