### ISSUE TITLE
Integration con MediaElch 2.10.5-dev

### ISSUE THREAD

**Issue by Santicoma** [b-jesch/skin.estuary.modv2#126]
I don't know if my request is here appropriate, but it is going; How to configure Estuary Mod2 in Kodi Nexus 2.2 to show all the discography that I have saved in MediaElch, even it don't appears in my collection?

**Comment by b-jesch** [comment]
Sorry, I do not have any experience with MediaElch. Maybe there's more information on this thread on kodi.tv: https://forum.kodi.tv/showthread.php?tid=136333&page=146

**Comment by C4Wiz** [comment]
Skin has nothing to do with it, mediaelch needs to save the files the way kodi requires. TMM does this just fine
