### ISSUE TITLE
Installation from ZIP file?

### ISSUE THREAD

**Issue by Odroid13** [b-jesch/skin.estuary.modv2#129]
Thank you for your work. I try to install the skins without Repo but directly with the zip file.

I renamed the zip file inside without unzipping it but it doesn't work and the same when I unzip it.

Do you have an idea ?

( I have no internet in my holiday home located in nature, no telephone network and no internet network, I use an HDD with 4TB of video )

On Mac & Windows same error.
Watch the video please.

Thanks
https://github.com/b-jesch/skin.estuary.modv2/assets/97029183/bc1811ae-8f78-4a3e-811e-919700120b95

**Comment by Odroid13** [comment]
> You have to install the dependencies first. Thats why we prefer installation from repo - in this way the dependend addons will be installed first. But that's indeed hard without network.
> 
> Install first:
> 
> * script.skinshortcuts: http://mirrors.kodi.tv/addons/nexus/script.skinshortcuts/script.skinshortcuts-2.0.3.zip
> * script.embuary.helper: http://mirrors.kodi.tv/addons/nexus/script.embuary.helper/script.embuary.helper-2.0.8.zip
> * script.image.resource.select: http://mirrors.kodi.tv/addons/nexus/script.image.resource.select/script.image.resource.select-3.0.2.zip
> * script.module.pvr.artwork: https://github.com/b-jesch/script.module.pvr.artwork/archive/refs/heads/master.zip
> 
> Install the skin at least.

Thanks for your feedback.

Everything works great :D

-------------------------------------------------- --------------------------------------------------

Small question, I would like to change the 3 png by default by personalized images.
power.png
settings.png
search.png

To do it quickly, just replace the images found in skin.estuary.modv2\extras\home-images

With this method it works but I have to modify the skin at the base.



I would like to know if it is possible to do it directly from the settings.xml file which is in //kodi/userdata/addon_data/skin.estuary.modv2
Or maybe another file.

The goal is to simply add my modifications after installing the skin from Kodi with the file manager.

**Comment by b-jesch** [comment]
Don't replace the images. They will be overwritten on next update. Just choose images in Settings -> Skin settings outside of kodi here:

![Bildschirmfoto von 2023-08-15 19-16-57](https://github.com/b-jesch/skin.estuary.modv2/assets/10152384/3508c47a-b22f-49aa-9af1-4b92bcdd1726)

**Comment by Odroid13** [comment]
Fantastique :D

Thanks for all
