### ISSUE TITLE
Installation failed，I need your help,thank you very much

### ISSUE THREAD

**Issue by 244671360** [b-jesch/skin.estuary.modv2#13]
I install it in kodi 19, and  it says that "The dependency on script.module.pvr.artwork version 1.0.3 could not be satisfied." What should I do?

**Comment by b-jesch** [comment]
This is related to here: https://github.com/b-jesch/skin.estuary.modv2/issues/10

**Comment by 244671360** [comment]
There is empty in kodinerds repo on github ，where can I dowload it now

**Comment by b-jesch** [comment]
Download the Kodinerds Repo Addon Zip from their website: https://repo.kodinerds.net (red button) and perform a "Install from Zip". After that install the skin from the "Nerdsrepo". The "script.module.pvr.artwork" should be installed automatically on this way.
