### ISSUE TITLE
Small osd progressbar overlap the playerprocessinfo.

### ISSUE THREAD

**Issue by frodo19** [b-jesch/skin.estuary.modv2#132]
Hi, when the osd small, and toggle playerprocessinfo, the seekbar go to up, and overlap the processinfo.
Need stay on original position, just the clearart need move up.

**Comment by frodo19** [comment]
![screenshot00002](https://github.com/b-jesch/skin.estuary.modv2/assets/1296125/3c0d7f6b-2e6d-4f04-897e-feb6722b9cc8)
![screenshot00004](https://github.com/b-jesch/skin.estuary.modv2/assets/1296125/f9ac2d37-a77a-4f7f-b114-6f9f382a3608)

**Comment by b-jesch** [comment]
Has fixed. Available on Github or with next update on repo.
