### ISSUE TITLE
Movies played via Widgets attempt to play repeatedly after stopped

### ISSUE THREAD

**Issue by c0ldvengeance** [b-jesch/skin.estuary.modv2#139]
I’ve tired a few video addons and any movie that is played via a widget tries to launch about 3 times after stopping the movie.

TV shows do not seem to have this issue and the only difference I can tell is that the source file list is shows full screen and not within a window.

**Comment by b-jesch** [comment]
This happens mostly using third party video addons which provides streaming content and have their own navigation logic. This is not related to the skin but to Embuary Helper script/addon.

**Comment by c0ldvengeance** [comment]
I appreciate you pointing me in the right direction at least. Thank you
