### ISSUE TITLE
Smart Playlist Widgets Not Showing Up

### ISSUE THREAD

**Issue by stevepap540** [b-jesch/skin.estuary.modv2#14]
I have several smart playlists I use as widgets in my main menus, and they have disappeared since the last update. They don't show up anymore. Not sure if anyone else experienced this.

**Comment by b-jesch** [comment]
There are no changes that affects skin shortcuts (which is used for menu modifications by user) in the last update. Maybe you can reconfigure the main menus anyway?

**Comment by stevepap540** [comment]
Thanks. I have been messing around with it and realized it's not the smart playlists. I noticed that any Widget Appearance set to thumbs (with or without banner) does not show up. Having it set to posters and squares works though. Any ideas what might be going on?

**Comment by b-jesch** [comment]
Can you explain how to create a widget, change the appearance and assign it to the main menu? I would like to understand the fault and find a solution for this.

**Comment by b-jesch** [comment]
Problem solved. At the last code cleanup I've accidently deleted some code that affects the visibility of widget appereance types. I have partially reverted these modifications.

**Comment by b-jesch** [comment]
Closed due update.

**Comment by stevepap540** [comment]
Thanks! Confirmed to be working now! Love the skin!
