### ISSUE TITLE
Feature request: option to resize the posters for movies/tv/videos/music

### ISSUE THREAD

**Issue by cooljimy84** [b-jesch/skin.estuary.modv2#144]
I've been trying to change the height and width of the posters using a few forums posts but can't quite get the scale right. I was wondering if having an option in the skin to reduce the poster size (so you can fit more item on the home screen)

This is one of the guides i having been using.
[https://forum.kodi.tv/showthread.php?tid=313428](url)

**Comment by b-jesch** [comment]
Height and Width are defined in several includes scattered in serveral files. The link you've posted above is quite old and many things has changed between. The examples linked above are no longer applicable.

You have to change the code of all occurences of WidgetListPoster in all files. If you don't understand the internal structure of this skin, it's nearly impossible to modify that properly. It took me over a year to do this.

Regards.

**Comment by cooljimy84** [comment]
> Height and Width are defined in several includes scattered in serveral files. The link you've posted above is quite old and many things has changed between. The examples linked above are no longer applicable.
> 
> You have to change the code of all occurences of WidgetListPoster in all files. If you don't understand the internal structure of this skin, it's nearly impossible to modify that properly. It took me over a year to do this.
> 
> Regards.

Well that's a pain then. Just seems like a lot of wasted space for the posters.
A pipe dream it shall remain I suspect
