### ISSUE TITLE
Feature request: show CD-art only if available

### ISSUE THREAD

**Issue by JeroenED** [b-jesch/skin.estuary.modv2#145]
Hi, 

For some music in my library I have a CD-Art available, from some not. I can set to show the CD-art or not. If there is no CD art available it makes up something with the artist and title. What about a additional option to only show if available? Would this be something you can implement?

Kind regards
Jeroen

**Comment by b-jesch** [comment]
Yes, I've just implemented this. Available with next update.

![Bildschirmfoto von 2024-01-04 17-34-35](https://github.com/b-jesch/skin.estuary.modv2/assets/10152384/2b4ffc6b-85a7-4db3-bb98-266f78419949)
