### ISSUE TITLE
DialogVideoInfo.xml -> WidgetListThumbInfo

### ISSUE THREAD

**Issue by quickmic** [b-jesch/skin.estuary.modv2#146]
NextUpEpisodes has a bug. It works for TVShows but not its subcontent (Season or Episode).

`<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.DBID]/-2/?tvshowid=$INFO[ListItem.DBID]"/>` is correct for TVShows but for Season or Episode it should look like that.

`<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.TvShowDBID]/-2/?tvshowid=$INFO[ListItem.TvShowDBID]"/>`

I'm not a skin expert, so I don't know how to add a condition to the param.
Maybe a second container with a different include condition?

Something like
`<include content="WidgetListThumbInfo" condition="String.IsEqual(ListItem.DBType,tvshow)">`
`<include content="WidgetListThumbInfo" condition="String.IsEqual(ListItem.DBType,episode)|String.IsEqual(ListItem.DBType,season)">`

**Comment by b-jesch** [comment]
Done.

**Comment by quickmic** [comment]
There is still a bug:
`<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.DBID]/-2/?tvshowid=$INFO[ListItem.TvShowDBID]"/>`

first dbid should also pint to tvshowdb

`<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.TvShowDBID]/-2/?tvshowid=$INFO[ListItem.TvShowDBID]"/>`

**Comment by b-jesch** [comment]
That contradicts your statement above:

```
<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.DBID]/-2/?tvshowid=$INFO[ListItem.DBID]"/> 

is correct for TVShows but for Season or Episode it should look like that.

<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.TvShowDBID]/-2/?tvshowid=$INFO[ListItem.TvShowDBID]"/>
```

**Comment by quickmic** [comment]
What?

There is no inconsistency in my statements.
All samples included the same code.
`<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.TvShowDBID]/-2/?tvshowid=$INFO[ListItem.TvShowDBID]"/>`

btw, the parameter is pointless, could be shortened to:
`<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.TvShowDBID]/-2/"/>`

**Comment by b-jesch** [comment]
Do you read your own posts?

> `<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.DBID]/-2/?tvshowid=$INFO[ListItem.DBID]"/>` is correct for TVShows

and

> but for Season or Episode it should look like that.
> 
> `<param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.TvShowDBID]/-2/?tvshowid=$INFO[ListItem.TvShowDBID]"/>`

Also if the content path is the same for tv shows, seasons and episodes there is no need to distinguish between tvshows and seasons + episodes:

> Maybe a second container with a different include condition?
> 
> Something like
> ```
> <include content="WidgetListThumbInfo" condition="String.IsEqual(ListItem.DBType,tvshow)">
> <include content="WidgetListThumbInfo" condition="String.IsEqual(ListItem.DBType,episode)|String.IsEqual(ListItem.DBType,season)">
> ```

**Comment by quickmic** [comment]
> Do you read your own posts?

Yes I did, not sure what's the misunderstanding.

The `videodb://inprogresstvshows/` db query expects a parameter of a TVShow DBID (Kodi database type "tvshows" for field "media_type" )

The condition filter `condition="String.IsEqual(ListItem.DBType,tvshow)` filters tvshows only, ergo the Listitem is a TVShow. Therefore the listitem DBID is the tvshow ID.

for episodes or seasons it's different. You still want to query the in progress TVShows but for a listitem type season/episode.
As the DBID of a episode listitem or  season listitem is NOT the tvshow ID, you need to use the TVShowID of those listitems cause you still want to query the tvshows (and not the episodes or seasons).


But maybe you have something different in mind, how this should work?

param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.**_TvShowDBID_**]/-2/?tvshowid=$INFO[ListItem.**_TvShowDBID_**]"/

**Comment by quickmic** [comment]
your fix:

param name="content_path" value="videodb://inprogresstvshows/$INFO[ListItem.**_DBID_**]/-2/?tvshowid=$INFO[ListItem.**_TvShowDBID_**]"/

**Comment by b-jesch** [comment]
Ok, I see my fault.
