### ISSUE TITLE
I made a Chinese localized file based on the English file

### ISSUE THREAD

**Issue by Dreamsky00824** [b-jesch/skin.estuary.modv2#149]
[resource.language.zh_cn.zip](https://github.com/b-jesch/skin.estuary.modv2/files/14109032/resource.language.zh_cn.zip)

**Comment by b-jesch** [comment]
There are 106 Errors within the file, mainly mixed up quotation marks. It is not allowed to merge them up e.g. 

> #: /xml/SkinSettings.xml
> msgctxt "#31298"
> msgid "Manage items from 'Movies' widget"
> msgstr "管理 "电影 "部件中的项目"

The chinese string has to be instead `msgstr "管理 '电影 '部件中的项目"` . Double quotation marks within the string musst be replaced with single marks " --> ' or if not possible the double marks within must be masked " --> \\": `"管理 \"电影 \"部件中的项目"`.

**Comment by b-jesch** [comment]
But anyway, thank you for the work you've done. I've corrected the spellings. Was simply.
