### ISSUE TITLE
Update for Kodi 21?

### ISSUE THREAD

**Issue by CJthisis** [b-jesch/skin.estuary.modv2#151]
Is this skin going to get an update for Kodi 21, or do I have to switch to another skin?

**Comment by C4Wiz** [comment]
> Is this skin going to get an update for Kodi 21, or do I have to switch to another skin?

I guess reading is not your Forté?

<img width="921" alt="Screenshot 2024-02-26 at 8 05 57 AM" src="https://github.com/b-jesch/skin.estuary.modv2/assets/3883521/c89f0125-c96a-4e87-89bb-20d176da929a">

**Comment by CJthisis** [comment]
I was still in the branch for Nexus, didn't realize it 😅. Case closed
