### ISSUE TITLE
Omega progress icons

### ISSUE THREAD

**Issue by derrgoo** [b-jesch/skin.estuary.modv2#152]
Is it possible to add progress icons on widgets like it has on nexus to see which are in progress view?

**Comment by b-jesch** [comment]
Visibility of progress icons is identical on Nexus and Omega - except the video version icon.

**Comment by derrgoo** [comment]
See example for nexus using a 3rd party add on like fenlight. ![image](https://github.com/b-jesch/skin.estuary.modv2/assets/63697905/d2c69111-c1fe-48ea-8ea8-afb6e7a447f3)

However, if I load omega this will not show. Is this skin change or add on?

**Comment by b-jesch** [comment]
Fenlight is the replacement of the (banned) fen addon. No support here. But I suspect that fenlight does'nt support some infolabels on omega. Is the status label correct showing in stock estuary?

**Comment by derrgoo** [comment]
Sorry to mention add on. Was unaware of that but I also have library. I think your correct, I was thinking same because all nexus skins show. But omega seems to have different code.
