### ISSUE TITLE
Information above widget

### ISSUE THREAD

**Issue by Arthur1967** [b-jesch/skin.estuary.modv2#153]
I like the skin, but is there a way to get information above the widget maybe I Missed something

**Comment by b-jesch** [comment]
Could you describe the issue more precise? I don't know what you mean with "get information above the widget"

**Comment by Arthur1967** [comment]
Not really an issue just in the row of widgets. How do I get information on the program above the widget maybe I missed a setting

**Comment by Arthur1967** [comment]
![image](https://github.com/b-jesch/skin.estuary.modv2/assets/69996032/5902c1d5-d36d-4df9-8cab-ccbcd68c1c67)

**Comment by Arthur1967** [comment]
That's on a different skin, but is there a way to get that information on your skin because I do like your skin

**Comment by b-jesch** [comment]
Not possible. On Home screen there is simply no place for that. And, there is no option for a horizontal menu (and will never implemented).

**Comment by Arthur1967** [comment]
OK
