### ISSUE TITLE
Nexus: "Create new preview icons" is missing in the channel group manager

### ISSUE THREAD

**Issue by rainman74** [b-jesch/skin.estuary.modv2#154]
The menu item "Create new preview icons" is missing in the channel group manager

Estuary Mod v2 Skin:
![image](https://github.com/b-jesch/skin.estuary.modv2/assets/16306963/0c22cca3-e1ad-442e-902e-b8184f9564a5)

Standard Estuary Skin:
![image](https://github.com/b-jesch/skin.estuary.modv2/assets/16306963/9fcb1ea1-9587-4632-837e-f4ce94f0a05d)

**Comment by b-jesch** [comment]
Has fixed.
