### ISSUE TITLE
Can't install on v21 due to missing dependencies

### ISSUE THREAD

**Issue by CJthisis** [b-jesch/skin.estuary.modv2#155]
First of all: I'm on a Pi 5 on LibreElec 12, I did try to install the skin from the repo, which I downloaded a fresh version of a few minutes ago.

Basically all the dependencies seem to be missing, and even the only one that seems to be OK is also missing its respective dependencies.

Can I do something to fix this issue myself?

![image](https://github.com/b-jesch/skin.estuary.modv2/assets/99442347/74c05d1c-112b-49a5-a022-e160fc98e1d2)

**Comment by b-jesch** [comment]
First install the Kodinerds Repo addon (red button, [https://repo.kodinerds.net](https://repo.kodinerds.net)). After that, install skin from repo (settings >> addons >> install from repo >> Kodinerds Addon Repo >> Look & Feel >> Skins >> Estuary Mod V2 Omega). This will install the needed dependencies too.

**Comment by CJthisis** [comment]
> First install the Kodinerds Repo addon (red button, [https://repo.kodinerds.net](https://repo.kodinerds.net)). After that, install skin from repo (settings >> addons >> install from repo >> Kodinerds Addon Repo >> Look & Feel >> Skins >> Estuary Mod V2 Omega). This will install the needed dependencies too.

Welp, I did it exactly like you said before, but this time it worked. I don't know why, but it worked this time, thanks!
