### ISSUE TITLE
View_503_Gallery.xml parentheses issue

### ISSUE THREAD

**Issue by quickmic** [b-jesch/skin.estuary.modv2#157]
`<visible>Container.Content(episodes) + ![!$EXP[show_unwatchedthumbs]) + Integer.IsLess(ListItem.Playcount,1) + Container.Content(episodes)]</visible>`

should be:
`<visible>Container.Content(episodes) + ![!$EXP[show_unwatchedthumbs] + Integer.IsLess(ListItem.Playcount,1) + Container.Content(episodes)]</visible>`

**Comment by b-jesch** [comment]
Fixed. Thanks for contribution.
