### ISSUE TITLE
Version selector Audio Codec Flag issue.

### ISSUE THREAD

**Issue by C4Wiz** [b-jesch/skin.estuary.modv2#158]
In wall view the Atmos flag is Honored, but in the version selector and videoinfo screens it is not.

See attached screenshots:

![screenshot00003](https://github.com/b-jesch/skin.estuary.modv2/assets/3883521/08e86786-3ef8-4fb8-8d88-afd533336bbc)
![screenshot00004](https://github.com/b-jesch/skin.estuary.modv2/assets/3883521/6f45a452-157e-4ba8-854e-e7596b9fffea)
![screenshot00005](https://github.com/b-jesch/skin.estuary.modv2/assets/3883521/8576ea4a-a4a6-4cb5-8c0c-34b24253e2ae)

**Comment by b-jesch** [comment]
Atmos detection is by filename (contains "atmos" within). Normally TrueHD is the right output as this comes from media info by Kodi core (VideoPlayer.AudioCodec, ListItem.AudioCodec). Mediainfo returns for this files TRUEHD as codec info too:

e.g. Retribution.mkv:

> Audio #1
> ID                                       : 2
> Format                               : MLP FBA 16-ch
> Format/Info                        : Meridian Lossless Packing FBA with 16-channel presentation
> Commercial name             : Dolby TrueHD with Dolby Atmos
> Codec ID                           : A_TRUEHD
> ...

In the next versions I plan to remove the codec information by file name. This will also affect DTS-X.

**Comment by C4Wiz** [comment]
I understand that, i have atmos in the file name and it is not detected properly is what im saying. Why would you remove filename detection if kodi does not do it natively?

**Comment by b-jesch** [comment]
Because natively it's TrueHD (and Dolby Atmos included in most cases). Detection of any kind via file name is fakeable and doesn't reflect what is actually inside.

**Comment by C4Wiz** [comment]
> Because natively it's TrueHD (and Dolby Atmos included in most cases). Dedection of any kind via file name is fakeable and doesn't reflect what is actually inside.

so the only way to know if the movie you are going to watch is atmos or truehd is to play the movie and see what comes up on the reciever display?

that makes no sense to me! the point of file name detection is to add what kodi can not natively!

if someone wants to fake having atmos thats on them, why remove it for those of us that rely on it for proper cataloging?

**Comment by C4Wiz** [comment]
but since this is your skin and you know it in and out, do you mind telling me how to fix it for my own use?

**Comment by b-jesch** [comment]
;) So we both have a different view point of such things. That's life. But I accept your point of view too and I'm sure finding a proper solution. For now there is to much file name detection of audio codecs what have to simplified anyway: https://github.com/b-jesch/skin.estuary.modv2/blob/b6224f2cbc0a1952b395527a5a708cf8efe8800a/xml/Variables.xml#L1694-L1733

**Comment by C4Wiz** [comment]
This fixed the issue!

so i created this:

```
<variable name="Container6_AudioCodecFlagVar">
		<value condition="String.Contains(Container(6).ListItem.Filenameandpath,ATMOS)">flags/audiocodec/atmos.png</value>
		<value condition="String.Contains(Container(6).ListItem.Filenameandpath,DTS-X)">flags/audiocodec/dts-x.png</value>
		<value condition="String.Contains(Container(6).ListItem.Filenameandpath,DTSX)">flags/audiocodec/dts-x.png</value>
		<value>$INFO[Container(6).ListItem.AudioCodec,flags/audiocodec/,.png]</value>
	</variable>
```

then added this to Includes_DialogSelect.xml

 ```
                    <control type="group">
				<left>-30</left>
				<right>200</right>
				<bottom>0</bottom>
				<height>70</height>
				<visible>Control.HasFocus(6)</visible>
				<include content="MediaFlagsInfoDialogLeft">
					<param name="align" value="left" />
					<param name="infolabel_prefix" value="Container(6)." />
					<param name="show_ratings" value="false" />
					<param name="resolution_var" value="$VAR[Container6_3DFlagVar]" />
					<param name="audiocodec_var" value="$VAR[Container6_AudioCodecFlagVar]" />
				</include>
```

**Comment by b-jesch** [comment]
Has been fixed: https://github.com/b-jesch/skin.estuary.modv2/commit/baf07da458e6504228296260dd6134f93e9b5e38
