### ISSUE TITLE
Pause is not subtitle friendly

### ISSUE THREAD

**Issue by felichas** [b-jesch/skin.estuary.modv2#163]
Pausing a video displays information that hides subtitles. 

A possible solution to this:

- Display the actual (super handy) information only when pressing <ok>
- Only display some minimal information when pressing <pause> (like estuary started doing some time ago)

This arrangement, or a similar one would help people who rely on subtitles to understand fast paced section of foreign videos while providing the helpful information being provided today.

**Comment by b-jesch** [comment]
Set this in settings >> skin settings:

![Zwischenablage_10-27-2024_01](https://github.com/user-attachments/assets/7da04ee3-8489-4866-bb53-71c6be4a2384)

**Comment by felichas** [comment]
My fault.
Thanks a lot for your help here and for all the work done on this skin. You have +1 user :)

**Comment by b-jesch** [comment]
You're welcome.
