### ISSUE TITLE
Show bitrate & sampling rate when playing audio

### ISSUE THREAD

**Issue by STPKITT** [b-jesch/skin.estuary.modv2#164]
Hi,
this is a short feature request:
Currently the skin displays the codec type, channels and bit depth when playing audio.
I think it should also show the bitrate and the sampling rate, just like in most audio players and some Kodi skins out there.
Greets!

**Comment by b-jesch** [comment]
Fixed by https://github.com/b-jesch/skin.estuary.modv2/commit/3b1a7ab87a297fa22bad4dc4a625cf08c17c50d9

**Comment by STPKITT** [comment]
Thanks very much! I'm happy to report that I already tried it & it looks very good and makes the Audio OSD more useful.
