### ISSUE TITLE
Do not show snowflakes and such when viewing pictures full screen

### ISSUE THREAD

**Issue by STPKITT** [b-jesch/skin.estuary.modv2#165]
Hi,
I found an issue in regards to the nice Christmas season theme and possibly also the other season's themes.
Currently when viewing pictures in fullscreen the snowflakes keep falling! So a bugfix should be created which stops overlaying the snowflakes when viewing pictures just like it is already the case when viewing video.
Greets!

**Comment by b-jesch** [comment]
But it's a very nice view seeing snowflakes falling by the pyramids of Egypt :-) Anyway, this has been fixed of coarse.

**Comment by b-jesch** [comment]
Fixed by https://github.com/b-jesch/skin.estuary.modv2/commit/3b1a7ab87a297fa22bad4dc4a625cf08c17c50d9

**Comment by STPKITT** [comment]
That was an ultra quick fix. Thanks very much!
