### ISSUE TITLE
Feature request: option to always switch to fullscreen when audio playback is started

### ISSUE THREAD

**Issue by STPKITT** [b-jesch/skin.estuary.modv2#167]
Hi,
I'd like Kodi to automatically go fullscreen when the user starts audio playback.
I've read through the Kodi docs and forum and it seems that the theme needs to have an option for that to support it.
So maybe you could please add that to Estuary Mod V2's skin settings.

**Comment by b-jesch** [comment]
Settings >> Media >> Music >> Switch to Visualisation on Playback: https://forum.kodi.tv/showthread.php?tid=366400&pid=3209149#pid3209149 Sorry for the naming of this option, it's a kodi setting.

**Comment by STPKITT** [comment]
Hi,
I just tried this and it does indeed have my desired result despite not having visualisations enabled or even installed.
You're right about the naming though, I think I'll try to get this changed.
Thanks!
