### ISSUE TITLE
Episodes Repeating 2 Times After Being Played

### ISSUE THREAD

**Issue by 8igMacca** [b-jesch/skin.estuary.modv2#17]
I'm having an issue that is only occurring when using this skin (it doesn't happen with the standard Estuary or Estuary Mod skins).

Basically whenever you watch an episode, when you exit back to Kodi (even if the video is still playing in the background), kodi will attempt to launch the same episode 2 more times. This appears to be add-on independent (happens with Fen, Seren and Venom).

All of the various settings for 'Auto-Repeat' are set to disable.

As I've mentioned, this behaviour stops when using the standard Estuary or Estuary Mod skins.

I can't see what, if any, settings within Estuary Mod v2 could be causing this?
The only things I used Estuary Mod v2 to do are customising the main menu/sub menus - No other settings/config have been changed.

This happens on Kodi v19.1 and 19.3

Here's a link to a log file capturing the issue:

https://paste.kodi.tv/oyunubowuy.kodi

Thanks

Macca

**Comment by b-jesch** [comment]
The logfile is not properly linked and therefore not accessible.

**Comment by 8igMacca** [comment]
> The logfile is not properly linked and therefore not accessible.
Sorry about that, I've updated the link. 

Hopefully it's viewable now.

Cheers

Macca

**Comment by b-jesch** [comment]
I can't elaborate the behavior of launching an episode multiple times, but I also don't use any of the addons mentioned above. After looking at the log, I noticed that the fen addon has a high activity. Possibly this addon is responsible for the behavior. As all mentioned addons are on the list of banned addons (see here: https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons#Add-on_blacklist ) I'm not willing to investigate more time into this issue and close it. If you notice the same behavior on a clean and fresh installation, feel free to reopen this issue.

**Comment by motsch94** [comment]
Hi, I have the same issue on clean install.
