### ISSUE TITLE
Fanart transparency

### ISSUE THREAD

**Issue by derrgoo** [b-jesch/skin.estuary.modv2#172]
Is there a setting to increase transparency behind the widgets? If not can you point me to the appropriate code to adjust.

**Comment by b-jesch** [comment]
For fanart transparency: 0% no fanart, 100% full visible:

![Zwischenablage_12-31-2024_01](https://github.com/user-attachments/assets/0a83ff83-9010-43ea-b29c-1b167b2feea7)

Transparency of video background has been modified, but not uploaded yet to Repository: https://github.com/b-jesch/skin.estuary.modv2/issues/171
