### ISSUE TITLE
severe slowdown on Android with Nvidia Shield  

### ISSUE THREAD

**Issue by mg1234567** [b-jesch/skin.estuary.modv2#20]
Estuary Mod v2 3.3.0+matrix.8
Kodi 19.3
Android 9 
Nvidia Shield 

Because of the size of my kodi install everything is on a usb 3.1 128gb thumb drive. 
Since the move, every menu is seriously slow.  
I've uninstalled kodi and started with a fresh install. 
Since then, stock kodi has been snappy and fast without any issues. 
Since re-installing my favorite theme Estuary Mod V2 3.3.0, my menus are again slow and it can take **3-30 seconds** when switching from one menu to another.  
For example, from movies to tv to settings etc... 

At the moment the xmas theme with snow & reindeer are on the screen. 

Anyone else experiencing slowdown problems with Estuary Mod v2 3.3.0, but not with the stock theme? 

Anything anyone can think of to fix the slowdown? (I dislike the huge main menu of stock Estuary).

**Comment by b-jesch** [comment]
How did you install the skin? Directly from download/zip or from Kodinerds repository?

**Comment by mg1234567** [comment]
Thanks for getting back to me. 
First time via the nerds. 
2nd time via a zip. 

Also, the slowdown is only the first time I go to a new menu (movies to tv to power to etc) 
Once it's been loaded, it goes much faster. 
But, this slowdown happens even if kodi has been up and running for hours.  
Seems like menus are not loading properly or not caching properly...

**Comment by b-jesch** [comment]
Its a good idea to install the skin via update from repo. Do you perform a start action or a startup window when the skin is coming up? (Settings -> Interface -> Startup). If so, set both to none.

**Comment by mg1234567** [comment]
None and Home.  I hit reset just to be sure. 


Settings > Media > Library 
I do have update library on startup on

**Comment by b-jesch** [comment]
Please set Kodi into the debug mode and provide a debug log.

**Comment by mg1234567** [comment]
https://pastebin.com/7J0qD7bF

**Comment by b-jesch** [comment]
Sorry:

"Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it."

Maybe you zip the log file and append it here or open a post here:  https://forum.kodi.tv/showthread.php?tid=306757

**Comment by mg1234567** [comment]
Sorry, for me it says pending moderation... I've never seen this before from pastebin. 

[kodi log.zip](https://github.com/b-jesch/skin.estuary.modv2/files/7657317/kodi.log.zip)

**Comment by b-jesch** [comment]
I can see from the log file that the return key was used 2x. I can't see any significant delay from the receipt of the keystroke to the initialization of the windows.

> 2021-12-05 09:15:27.290 T:22248   DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
> 2021-12-05 09:15:27.292 T:22248   DEBUG <general>: Activating window ID: 10016
> 2021-12-05 09:15:27.598 T:22248   DEBUG <general>: ------ Window Deinit (Settings.xml) ------
> 2021-12-05 09:15:27.598 T:22248   DEBUG <general>: FreeVisualisation() done
> 2021-12-05 09:15:27.607 T:22248   DEBUG <general>: ------ Window Init (SettingsCategory.xml) ------
> 2021-12-05 09:15:27.607 T:22248    INFO <general>: Loading skin file: SettingsCategory.xml, load type: KEEP_IN_MEMORY

and

> 2021-12-05 09:15:00.605 T:22248   DEBUG <general>: Keyboard: scancode: 0x17, sym: 0x13, unicode: 0x0000, modifier: 0x0
> 2021-12-05 09:15:00.811 T:22248   DEBUG <general>: Skipped 1 duplicate messages..
> 2021-12-05 09:15:00.811 T:22248   DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
> 2021-12-05 09:15:00.811 T:22248   DEBUG <general>: Activating window ID: 10004
> 2021-12-05 09:15:01.125 T:22248   DEBUG <general>: ------ Window Deinit (Home.xml) ------
> 2021-12-05 09:15:01.125 T:22248   DEBUG <general>: FreeVisualisation() done
> 2021-12-05 09:15:01.128 T:22248   DEBUG <general>: ------ Window Init (Settings.xml) ------
> 2021-12-05 09:15:01.128 T:22248    INFO <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY

There is no much delay (max 0.5 sec). I can not see any error here unfortunately. However, I noticed that the queries on Google drive take up to 15 seconds and more. Maybe this is the problem, but that's just a guess.

**Comment by mg1234567** [comment]
Thank you. I'm looking into that... 
If you don't mind educating a noob, where and how are you seeing the google drive delays?  
I wish I had seen this and understood this...

**Comment by b-jesch** [comment]
Search for "save exports" in your log. You'll see a lot of time consumption for a few actions, eg:

> 2021-12-05 09:16:23.511 T:22303   DEBUG <general>: easy_acquire - Created session to http://www.msftncsi.com
> 2021-12-05 09:16:25.505 T:22319   DEBUG <general>: [plugin.googledrive][service-export-153499981040]: 'save_export': 32056.44 ms

**Comment by b-jesch** [comment]
If there are new insights, the issue can be reopened with pleasure.
