### ISSUE TITLE
Covers

### ISSUE THREAD

**Issue by Mtruco** [b-jesch/skin.estuary.modv2#21]
Good evening,
 I'm using your skin, but I'm having a little trouble with the vod. I have no cover on the folder of certain series and when I take off the skin they are presents.
 Is there a way to correct this error?
 Thank’s
 Marc

**Comment by b-jesch** [comment]
Could you reallocate/reassign cover artwork over the info window (see screenshot) ?

![Bildschirmfoto von 2021-12-06 20-33-51](https://user-images.githubusercontent.com/10152384/144910708-25ffe004-eab5-4eb1-997c-b93e3a3c2613.png)

**Comment by Mtruco** [comment]
Good evening,
 I tried but it doesn't work, when I put the original skin, I have the covers and the info.

**Comment by b-jesch** [comment]
Are you able to extract a file from zip and replace them within the skin?

**Comment by Mtruco** [comment]
Yes or course

**Comment by Mtruco** [comment]
In .kodi/addons/skin.estuary.modv2/ i don’t have folder xml, i have only the file settings.xml

**Comment by Mtruco** [comment]
The error is in the sources folder, if I go to the title tab of a and z the info is there.

**Comment by b-jesch** [comment]
The settings.xml resides in the userdata folder (`.kodi/userdata/addon_data/skin.estuary.modv2`) . This is the wrong place! What do You use (OS, 

> if I go to the title tab of a and z the info is there.

I don't understand that. What is a title tab and what do you mean with a and z?

**Comment by b-jesch** [comment]
Aah sorry you mean the Titles within the category widget (Movies, TV shows) and the folder symbol is present in the "Videos" section (mediasources)? If that, those videos/tv shows are simply not scraped from your preferred scraper. Right click on the folder symbol and choose "scan to library".

**Comment by Mtruco** [comment]
Exactly this is the titles category widget.
 In my series appears with the cover art and episode info, but in my source folder I don't have any info on the folder but only on episodes and not on all series.

**Comment by b-jesch** [comment]
> but in my source folder I don't have any info on the folder but only on episodes and not on all series.

As I said, those content is'nt scraped correctly into the library. You have to scan this the manual way as I mentioned above.

**Comment by Mtruco** [comment]
I have already done a manual scrap on the file and it always looks the same.
And we are several friends having the same problem.

**Comment by b-jesch** [comment]
Same skin or different skin?

**Comment by Mtruco** [comment]
In fact it is not the skin that creates this defect,
 I have the same with the original skin

**Comment by Mtruco** [comment]
![image](https://user-images.githubusercontent.com/95547704/145082879-433dad89-0eac-4b59-a3c8-a9a90b4e9540.jpg)
![image](https://user-images.githubusercontent.com/95547704/145082907-c7b7bcb0-74b4-4cee-820a-d2496d972f7b.jpg)
![Uploading image.jpg…]()

**Comment by b-jesch** [comment]
Ok, it's a scraper issue and not skin related. Feel free to open an issue on forum.kodi.tv and discuss there. Maybe the community will find a solution. I close the issue here.
