### ISSUE TITLE
Please add to NL language file

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#22]
msgctxt "#40372"
msgid "Upcoming episodes"
msgstr "Aankomende afleveringen"

msgctxt "#40373"
msgid "Show MPAA rating"
msgstr "Laat MPAA beoordeling zien"

msgctxt "#40374"
msgid "(until "
msgstr "tot"

msgctxt "#40375"
msgid "Show Color Depth"
msgstr "Laat diepte kleur zien"

msgctxt "#40376"
msgid "Show additional Infos within the PVR widgets"
msgstr "Meer informatie binnen de PVR widgets"

msgctxt "#40377"
msgid "Close Video OSD automatically after"
msgstr "Sluit OSD menu automatisch na"

msgctxt "#40378"
msgid "disabled"
msgstr "Uitgezet"

msgctxt "#40380"
msgid "3 seconds"
msgstr "3 seconden"

msgctxt "#40381"
msgid "5 seconds"
msgstr "5 seconden"

msgctxt "#40382"
msgid "7 seconds"
msgstr "7 seconden"

msgctxt "#40383"
msgid "10 seconds"
msgstr "10 seconden"

msgctxt "#40384"
msgid "15 seconds"
msgstr "15 seconden"

msgctxt "#40385"
msgid "Show Channel Numbers"
msgstr "Laat kanaal nummers zien"

msgctxt "#40386"
msgid "Show Date of First aired"
msgstr ""

msgctxt "#40387"
msgid "Item Path of Picture Widgets"
msgstr "Pad naar foro widgets"

msgctxt "#40388"
msgid "Default Action on 'Movie' and 'TV-Show' Widgets"
msgstr "Standaard actie bij fils en serie widgets"

msgctxt "#40389"
msgid "Play Item"
msgstr "Afspelen"

msgctxt "#40390"
msgid "Show Info"
msgstr "Informatie laten zien"

**Comment by b-jesch** [comment]
Thank you. Will be available with the next update.
