### ISSUE TITLE
Corrected some typos in NL language file

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#23]
msgctxt "#40386"
msgid "Show Date of First aired"
msgstr "Voor het eerst verschenen"

msgctxt "#40387"
msgid "Item Path of Picture Widgets"
msgstr "Pad naar foto widgets"

msgctxt "#40388"
msgid "Default Action on 'Movie' and 'TV-Show' Widgets"
msgstr "Standaard actie bij films en serie widgets"

**Comment by b-jesch** [comment]
Thank You. Will be available on next update.
