### ISSUE TITLE
[Suggestion] Add more HDR and DV name patterns

### ISSUE THREAD

**Issue by zwoggel** [b-jesch/skin.estuary.modv2#25]
From what I can see the skin recognizes the strings “hdr”, “hdrplus” and “dv” to determine the needed media flags.
I have seen some files using “DoVi”, “dolbyvision” or “hdr+” in their file/folder name as well (although I’m not sure about the last one because of the plus sign) .

Is it possible to add those to the skin as well, at least the ones for Dolby Vision?

Many thanks

**Comment by b-jesch** [comment]
This is possible except for "hdr+" as the '+' breaks the internal comparsion.

**Comment by zwoggel** [comment]
Yeah, I think I got that mixed up with something else. ‘+’ signs are not even considered safe in file names, at least not in Windows.
If you could add the DV alternatives though, it would be much appreciated.

**Comment by b-jesch** [comment]
Added keyparts for DolbyVision: .dovu., .dolbyvision.
Note that the recognision is not case sensitive so .DoVu. or .DolbyVision. will be also triggered.

Will be available with next update.
