### ISSUE TITLE
[Feature Request] Holiday Theme dates.

### ISSUE THREAD

**Issue by gohamstergo** [b-jesch/skin.estuary.modv2#28]
Would it be possible to modify the holiday theme date for Christmas to end sooner? Its now jan1 but it continues to show the Christmas theme. Perhaps it should end 12/26? I know I can disable them completely, but I like them in general. Just think the Christmas one hangs on too long. Or many expose the dates for editing in the UI?

Thanks for the update for Matrix either way!

**Comment by b-jesch** [comment]
The Christmas theme ends today ;)

But independent from that, the christmas season ends much later in some countries, even in europe: https://aleteia.org/2020/01/06/when-does-the-christmas-season-end/

But as the seasonal times have to set manually in the configuration every year, I'll set this from 1.Advent to 26. Dec for 2022.
