### ISSUE TITLE
0 movies in "Collection"

### ISSUE THREAD

**Issue by albertinozz** [b-jesch/skin.estuary.modv2#30]
Here i am again ^_^;
I noticed another little issue.
Any movie collection indicates "0 movie" as you can see from the screenshots below.

![Senza titolo-1](https://user-images.githubusercontent.com/96786691/148419249-209a7221-22f7-41df-8c95-5a196ae9c1a3.jpg)
![Senza titolo-2](https://user-images.githubusercontent.com/96786691/148419280-3a49f093-0c70-47c5-bfc3-71a0bd4f2700.jpg)

How can I solve?

**Comment by b-jesch** [comment]
This has been fixed now and will be available with the next update.
