### ISSUE TITLE
Please add to NL translation 

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#31]
msgctxt "#40391"
msgid "Sort Order"
msgstr "Volgorde van sorteren"

msgctxt "#40392"
msgid "Show Path Navigation (Breadcrumbs) in List Views"
msgstr "Laat navigatie pad zien in lijdt opties"

msgctxt "#40393"
msgid "Show only 'current item / item count' Information"
msgstr "Alleen 'huidige item laten zien / optelsom' Informatie"

msgctxt "#40394"
msgid "Set Animated Poster"
msgstr "Stel bewegende posters in"

msgctxt "#40395"
msgid "Remove Animated Poster"
msgstr "Verwijder bewegende posters"

msgctxt "#40396"
msgid "Animated Poster removed"
msgstr "Bewegende posters verwijderd"

msgctxt "#40397"
msgid "Animated Poster added"
msgstr "Bewegende posters toegevoegd"

msgctxt "#40398"
msgid "Local Path to animated Poster Folder"
msgstr "In welke map staan de bewegende posters"

msgctxt "#40399"
msgid "The folder of the animated Poster Collection was not defined yet. Define a Folder on the local File System containing animated Posters within the Skin Settings."
msgstr "Folder voor bewegende posters nog niet aangemaakt. Deze dus aanmaken waar de posters in zitten."

msgctxt "#40400"
msgid "Could not assign animated Poster"
msgstr "Niet mogelijk een bewegende poster toe te wijzen"

msgctxt "#40401"
msgid "Hit Probability: "
msgstr "Kans dat deze gevonden wordt"

**Comment by b-jesch** [comment]
Implemented. Thank you!
