### ISSUE TITLE
NL translation

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#35]
msgctxt "#40402"
msgid "'Rotten Tomatoes' Rating Category"
msgstr "Rotten Tomatoes beoordelings categorie"

msgctxt "#40403"
msgid "Tomatometer all Critics"
msgstr "Tomatometer alle beoordelingen"

msgctxt "#40404"
msgid "Tomatometer average Critics"
msgstr "Tomatometer gemiddelde beoordelingen "

msgctxt "#40405"
msgid "Tomatometer all Audience"
msgstr "Tomatometer  alle publieke beoordelingen"

msgctxt "#40406"
msgid "Tomatometer average Audience"
msgstr "Tomatometer  gemiddelde publieke beoordelingen"

**Comment by b-jesch** [comment]
Available on next Update. Thank you!
