### ISSUE TITLE
FR: Description text instead of technical information

### ISSUE THREAD

**Issue by citronalco** [b-jesch/skin.estuary.modv2#37]
Don't know if this is there right place for a feature request - sorry if it's not.
I think it would be very helpful if this skin would show the movie's description text instead of those logos for audio mode, codec, resolution etc. in the player and in the widgets.

**Comment by b-jesch** [comment]
I don't think so. Most people want to see the technical information. There are regular requests for new flags like Dolby Vision or ratings and more. Also, there is only place for one line of text (instead the flags).

The settings menu of the skin has a setting that will the player with a minimalized view without media flags.

Feel free to discuss your FR in the forum thread of this skin. Maybe there is a better place for that.
