### ISSUE TITLE
Titles in small OSD

### ISSUE THREAD

**Issue by albertinozz** [b-jesch/skin.estuary.modv2#39]
I use small OSD. Is it possible to add title of movies or episodes on the OSD bar?
Thanks again for all!

**Comment by b-jesch** [comment]
Is this ok?
![Bildschirmfoto von 2022-01-29 21-32-11](https://user-images.githubusercontent.com/10152384/151677548-08c95b79-c76d-40c9-acf3-05066300c81a.png)

**Comment by albertinozz** [comment]
Seems to be great!

**Comment by b-jesch** [comment]
Ok. Available with next update.
