### ISSUE TITLE
[BUG] Views for movies can't be manually switched

### ISSUE THREAD

**Issue by hawkeyexp** [b-jesch/skin.estuary.modv2#4]
Switching the view in movies always switches back to default.

Possible it is caused while you have removed the views from settings and the script viewswitcher.py is still present?

A long time ago i created this script and Guilouz has embedded it :-)

**Comment by b-jesch** [comment]
Hmm, I don't see this behavior here. Maybe there is still an option activated in your settings.xml?

I'm thinking of putting the forced views back in, as the previous solution worked very well. That's why the script is still there.

**Comment by hawkeyexp** [comment]
Hm, i have the effect on both if my rpi4's - i will deeper check the logs what is causing it.

**Comment by b-jesch** [comment]
If the script is really the reason, just insert a sys.exit() directly behind the main routine as a quick fix. Don't forget to import sys ;)

**Comment by hawkeyexp** [comment]
the easy way is to disable forcedviews.enabled inside settings - which is still included in my case but not accessible inside the gui.
the script itselve is ok but must be changed cause you removed the skin helper service dep which was the source to interact with the views.

**Comment by b-jesch** [comment]
I could not experience this behaviour on a second machine too (@work). For now I've commented out the extension point for starting the service in the addon.xml.

**Comment by hawkeyexp** [comment]
schould be ok for now - i'm running libreelec so also a stripped down linux on my raspberry pi's :-)

**Comment by b-jesch** [comment]
Forced views has been reworked and reimplemented now.
