### ISSUE TITLE
<visible>

### ISSUE THREAD

**Issue by Grabber66** [b-jesch/skin.estuary.modv2#45]
https://github.com/b-jesch/skin.estuary.modv2/blob/7662d4c370c1910ead49a0da8b18bd747024ba1b/xml/Custom_1135_PVROverlay.xml#L15

Ist es möglich das du da noch ein visible mit einbaust:
Ich hab es bei mir mal so umgestrickt:
<visible>!Skin.HasSetting(enable_playerclearlogo) + !Skin.HasSetting(show_artistclearlogo)]</visible>

So bleiben beim schnellen zappen optional keine cleararts des letzten Senders stehen.

**Comment by b-jesch** [comment]
OK, ist mit drin.
