### ISSUE TITLE
not issue, but can I edit widget order?

### ISSUE THREAD

**Issue by pkishino** [b-jesch/skin.estuary.modv2#47]
Didn't see other option to raise a question..
First of all thanks for the skin, great work.
is there a way to change the order of the widgets for e.g. TV?
currently I see Recently added at the top before next up..
I would like to put recently added further down.
thanks

**Comment by b-jesch** [comment]
Yes, you have to edit the Home.xml within the addon folder (addons/skin.estuary.modv2/xml/Home.xml). Are you able to do this?

**Comment by pkishino** [comment]
thanks!
once I opened this file it was quite straightforward

**Comment by pkishino** [comment]
Hmm, after making changes (even setting Home.xml to be read only) , if Kodi restarts it reverts those Changes it seems, what to do to override this? Sorry for asking

**Comment by b-jesch** [comment]
I've provided an update from 3.4.0+matrix.6 to 3.4.0+matrix.7 yesterday. Maybe your changes were overwritten via update? It's also possible that changes made with skinshortcuts (add/remove/modify menu items) also initiate a skin reset as skinshortcuts rebuild the menues in this case.
