### ISSUE TITLE
When deconnecting from a profile, it goes to the master profile instead of going to the profile select screen

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [b-jesch/skin.estuary.modv2#5]
Hi,

There is a problem with this skin that I also had with the previous official version of Estuary Mod (doesn't happen with any other skin). When logging off from a profile, instead of going back to the profile select screen, it logs in by itself to the master user. That's a problem because it gives full access to the master user, even if it is locked with a PIN. Could you look into that ?

Thanks again for your work, it works great other than that. Have a great day

**Comment by b-jesch** [comment]
Hi,

This may take a while, as my skills in this area are not the best. I have to read up on it first.

**Comment by LeVraiRoiDHyrule** [comment]
No problem, thanks for your answer.
I understand this is not easy to fix as it is here from the original version. But maybe some experts can help on the official Kodi forum

**Comment by b-jesch** [comment]
Closed for Nexus. Please update to Nexus to solve this issue
