### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by MikeKOD** [b-jesch/skin.estuary.modv2#57]
Hello I would need to add some custom icons, I add them in the path where the other icons are (if I'm not mistaken from memory in extra / icon).  after some time the icons disappear.  Do you have to edit any files to be able to keep them?

Thanks for everything

**Comment by b-jesch** [comment]
The custum icons disappear every time an update of the skin is taken. To prevent them from deleting You have to put them outside of the skin estuary modv2 folder. Or, if these icons don't violate any copyrights I could them put into the extras directory and make them a part of this skin.

Requirement (like the other icons):

- black & white
- size 128x128 px

Append a Zip with the icons here and I take a look to them.

Regards

**Comment by MikeKOD** [comment]
I am asking for permission to pass one of the 2 icons.  In case I am denied permission, in which folder can I place my icons?

**Comment by MikeKOD** [comment]
I know that trick well.  I will send you the zip with the icons asap. 

Thanks

**Comment by MikeKOD** [comment]
Here are the 2 icons I would have liked to have included in your skin.

Thanks for everything

[icone.zip](https://github.com/b-jesch/skin.estuary.modv2/files/8476033/icone.zip)

**Comment by b-jesch** [comment]
Placed in extras/icons. Permanent available with next update.

**Comment by MikeKOD** [comment]
Hi, sorry for reopening the issue, but I would need to add this icon, if it is not a problem. Also it would be better if you would remove kod.png. that I sent you a few years ago, the project has changed name and logo. thanks and sorry again for the inconvenience.

![Image](https://github.com/user-attachments/assets/567e8966-7e3a-4a31-9e70-4e9c65fab7a9)
