### ISSUE TITLE
Palm Week Color cannot be changed

### ISSUE THREAD

**Issue by ambarusa** [b-jesch/skin.estuary.modv2#58]
Hi, 
I'm super happy that I can still use this skin in Matrix version. During configuration, the only thing I could not set are the colors. `Main color`, `Secondary color`, `Background color` are all disabled in the `Skin` menu. In `Interface` menu `Theme` and `Colours` settings can be changed, but nothing is changing after saving. 

Do you have an idea for me how to solve this? Thank you.

**Comment by b-jesch** [comment]
This has been already fixed. Update to 3.4.0+matrix.11 from Kodinerds repo.

**Comment by ambarusa** [comment]
I installed the repo and the skin today, so I must be up-to-date. Indeed, it was the seasonal theme, that locked the colors. I did not recognized it,  last year it looked different my other instance of this skin on Easter. Anyway, thanks for the help! Happy Holidays!
