### ISSUE TITLE
No longer get media runtimes on information pages

### ISSUE THREAD

**Issue by alinsavix** [b-jesch/skin.estuary.modv2#63]
Howdy,

As of a couple months ago (sorry, I don't know the exact version that it happened, but might have coincided with the Kodi 19.4 release), the information page for videos no longer shows the "media duration" and "media finish time" fields -- the icons and boxes for them are present, but they are empty. Those fields appear correctly with other skins, so it seems like this has to be something estuary-mod specific.

This is with Kodi 19.4 + estuary mod 3.4.1+matrix.5 (though as mentioned, it's been happening for a while, at least since the early 3.4.0 releases).

I'm not sure what information would be useful for troubleshooting, but I'd be happy to supply anything you request. 

Thanks!

**Comment by b-jesch** [comment]
> the information page for videos no longer shows the "media duration" and "media finish time" fields -- the icons and boxes for them are present, but they are empty.

I'm not sure what you exactly mean. Could you provide a screenshot?

**Comment by alinsavix** [comment]
Apologies for the (very) shitty cellphone screenshot -- my Kodi box is an nvidia shield, so no particularly easy way to get a proper screenshot.

Note the two empty boxes with stopwatches on the right side -- one is supposed to (and used to) show how long the video was, the other should show what time the video would end if it were started playing right now. 

![IMG_1316](**https://user-images.githubusercontent.com/25068788/176559539-234a3afe-c47c-4d34-86c4-5c0322eaef10.JPG**)

**Comment by alinsavix** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/25068788/176559895-64147603-e746-4b1a-aa81-06bb4775827f.png">

(trying again on the image, github seems angry with image uploads today for some reason...)

**Comment by b-jesch** [comment]
That's indeed crazy. Maybe a problem with the database? Also check your regional settings in kodi setup.

A screenshot of a movie from the actual version:
![Bildschirmfoto von 2022-06-30 10-29-23](https://user-images.githubusercontent.com/10152384/176630884-f0264159-c1e2-41f7-a49b-01ecadbb66b9.png)

and a music video:
![Bildschirmfoto von 2022-06-30 10-35-01](https://user-images.githubusercontent.com/10152384/176632056-2bf6d9ed-f112-4761-82a0-0fc7da93b960.png)
