### ISSUE TITLE
Logging out of a profile does not land on the profile selection screen and breaks my PVR plugin

### ISSUE THREAD

**Issue by rainman74** [b-jesch/skin.estuary.modv2#65]
**Problem:**

- If you use multiple profiles and do log out of a non-master profile (via the advanced power menu), you do not land on the profile selection screen as expected, but are automatically logged in directly to the master profile!
- However, something seems to go broken or not fully loaded, because from then on the PVR plugin (Zattoo) no longer works in the master profile. Also after restarting Kodi, it remains broken.
- The problem does not occur in the normal Estuary skin.
- Splash screen is disabled, as suggested in issue #5

**Suggested Solution:**

- It would therefore be better, one lands when logging off a profile through the extended power menu always on the profile selection screen, as it is also the normal behavior of Kodi actually.

**Comment by rainman74** [comment]
I have now built a menu in which I can jump to the profiles without the master profile is always loaded.

I used the Kodi build-in command: LoadProfile(profilename)

Could the skin select all available profiles and show them then as separate tiles in the power menu? This as a suggestion for improvement, if you do not find the error.

![2022-07-06_193548](https://user-images.githubusercontent.com/16306963/177610761-d05d227d-fd39-4d29-9584-0d9527ff5aca.png)

**Comment by b-jesch** [comment]
I have to investigate more time into this, but have not enough time yet. Sorry for that. Maybe in summertime.

**Comment by rainman74** [comment]
@b-jesch Yes I thought so, but I would really love to use the skin and that is the only point that is still holding me back. Your mod is really excellent otherwise and I love the advanced settings options.

If you find some time in summer I would also offer myself as a tester, I could quickly test out fixes and support you.

**Comment by b-jesch** [comment]
Thank you for contribution. I have to compare the  code between the origin Estuary and the modV2. For this I have to setup a kodi installation with user profiles. That need time.

**Comment by b-jesch** [comment]
Maybe this could things clear up: https://www.kodinerds.net/index.php/Thread/75468-Master-User-meldet-sich-automatisch-an/?postID=689173#post689173

**Comment by rainman74** [comment]
> Maybe this could things clear up: https://www.kodinerds.net/index.php/Thread/75468-Master-User-meldet-sich-automatisch-an/?postID=689173#post689173

ja, ich kenne die diversen Probleme mit den Profilen, aber das hier kann es nicht sein, denn es geht ja mit dem Standard-Estuary Skin fehlerfrei und ich lande immer auf dem Profil-Login-Screen! Sobald ich aber das Estuary-Mod-Skin aktiviere (und sonst nichts verändere) geht das nicht mehr. Ich habe auch viele andere Skins ausprobiert und damit klappt es auch. Es muss also irgendeine Einstellung in einer Skin-Datei sein, die das verursacht.

Vielleicht im Bereich des Power-Menüs, denn von dort wird es ja aufgerufen. Könnte man testweise das Standard-Estuary-Power-Menu wieder einbauen, wenn das nicht zu viel Aufwand verursacht? Das modifzierte Menü nutzt auch nicht wirklich etwas, wenn ich ehrlich bin und ich könnte darauf verzichten... ;-)

**Comment by b-jesch** [comment]
Ich vergleiche das mal.

**Comment by b-jesch** [comment]
Die betreffenden Befehle im Power Menü sind komplett identisch. Daran liegt es also nicht. Als Kandidat kommt evtl. das Skinhelper Addon in Frage, allerdings ist dieses für den Skin unverzichtbar.

**Comment by rainman74** [comment]
> Die betreffenden Befehle im Power Menü sind komplett identisch. Daran liegt es also nicht. Als Kandidat kommt evtl. das Skinshortcuts Addon in Frage, allerdings ist dieses für den Skin unverzichtbar.

I have removed the Skinshortcuts addon as a test, but the error persists.

**Comment by b-jesch** [comment]
Für die Nexus Version des Skins habe ich die Startup.xml neu geschrieben (Verwendung der neuen Skin-Timer unter Nexus). Die Profil-Probleme scheinen nach einem kurzen Test damit gelöst zu sein.

Da die letzte Version noch nicht im Kodinerds Repo ist, muss der Nexus-Branch manuell herunter geladen und das Verzeichnis im Zip von skin.estuary.modv2-Nexus auf skin.estuary.modv2 umbenannt werden. Anschliessend "aus Zip installieren" auswählen. Dass man auf Nexus updaten muss, sollte klar sein ;)

**Comment by rainman74** [comment]
> Für die Nexus Version des Skins habe ich die Startup.xml neu geschrieben (Verwendung der neuen Skin-Timer unter Nexus). Die Profil-Probleme scheinen nach einem kurzen Test damit gelöst zu sein.
> 
> Da die letzte Version noch nicht im Kodinerds Repo ist, muss der Nexus-Branch manuell herunter geladen und das Verzeichnis im Zip von skin.estuary.modv2-Nexus auf skin.estuary.modv2 umbenannt werden. Anschliessend "aus Zip installieren" auswählen. Dass man auf Nexus updaten muss, sollte klar sein ;)

Ja, das kann ich bestätigen! Es funktioniert nun 💯 

Vielen Dank!

**Comment by b-jesch** [comment]
Close as solved.

**Comment by b-jesch** [comment]
Note that this issue is still NOT fixed for Matrix. You have to update to Nexus.

**Comment by b-jesch** [comment]
Hast Recht. Nur leider gibt es wohl jemanden im kodi.tv Forum, der meint, noch etwas an den Zeigern drehen zu müssen. Deswegen nochmal der Hinweis.
