### ISSUE TITLE
Not directly an issue (Font settings)

### ISSUE THREAD

**Issue by MoarcyVega** [b-jesch/skin.estuary.modv2#66]
Hi,
i edited the font.xml-File to use the font which i use systemwide. 
Everytime the skin gets an update, it changes my fonts to the default ones. Is there any way to make my changes persist after an updete and prevent updates from changing the font, so i can keep my changes?

**Comment by b-jesch** [comment]
If you have a defined fontset with your own fonts, I could implement possibly that into the font.xml. The used fonts shouldn't violate any license conditions, at best they should be free fonts.

**Comment by MoarcyVega** [comment]
That would be so great. The font isn't made by myself, i only use it because i like it.
The Font is called "Economica" (https://fonts.google.com/specimen/Economica) and is licensed under the "Open Font License"

**Comment by b-jesch** [comment]
Ok, append a zip with your fontset here, I take a look into it, make some tests and adapt it to the font.xml possibly.

**Comment by MoarcyVega** [comment]
[Economica.zip](https://github.com/b-jesch/skin.estuary.modv2/files/9071349/Economica.zip)

That would be so great. Thanks a lot :)

**Comment by b-jesch** [comment]
I need the modified font.xml file too ;)

**Comment by MoarcyVega** [comment]
[Font.zip](https://github.com/b-jesch/skin.estuary.modv2/files/9071401/Font.zip)

**Comment by b-jesch** [comment]
Done now. In future you can select the Economica font by choosing setup -> Interface -> Fonts. But I must say - for bigger distances this font isn't optimal, also some labels/flags are not shown optimal. for lower distances like PC or Tablet it's ok.

Comes with next version next week.
