### ISSUE TITLE
NL/Dutch translations added

### ISSUE THREAD

**Issue by freaktabnl** [b-jesch/skin.estuary.modv2#7]
msgctxt "#40255"
msgid "Show movies of Reihe"
msgstr "Films uit bepaalde serie laten zien"

msgctxt "#40358"
msgid "Addon ID"
msgstr "Addon ID"

msgctxt "#40359"
msgid "Platform"
msgstr "Platform"

**Comment by freaktabnl** [comment]
msgctxt "#40357"
msgid "Restart Kodi"
msgstr "Herstart Kodi"

**Comment by b-jesch** [comment]
Thank you for contribution. Changes occurs in next update!
