### ISSUE TITLE
"Search" is missing in every sidemenu

### ISSUE THREAD

**Issue by rainman74** [b-jesch/skin.estuary.modv2#73]
"Search" is missing in every sidemenu, movies, TV series, music, music videos.

It is present in the standard Estuary skin.

Tested with Kodi 19.4 and 20.0 Alpha 2

![image](https://user-images.githubusercontent.com/16306963/185512583-00feb602-3beb-454f-a180-74404a2ba352.png)

**Comment by b-jesch** [comment]
Has been fixed and sorted under "Actions"

**Comment by rainman74** [comment]
Tested and confirmed! Thank you :-)
