### ISSUE TITLE
3.4.2+matrix.2 breaks thumbnails for recently added episodes

### ISSUE THREAD

**Issue by dcelasun** [b-jesch/skin.estuary.modv2#76]
A few hours ago the plugin automatically updated to 3.4.2+matrix.2 and all thumbnails for the "recently added episodes" section were replaced with the shows' generic fanart.

**Comment by b-jesch** [comment]
The widget views has just been improved and the thumbnails are back (if the option "hide thumbnails for unseen episodes" is unset). Available with the next update.

**Comment by dcelasun** [comment]
> Available with the next update.

Thanks! Any ETA on when 3.4.2+matrix.3 will be released?

**Comment by b-jesch** [comment]
Maybe 1 - 2 weeks on Kodinerds repository. There are some other issues in the chain.
