### ISSUE TITLE
Mapping EPG genres to XML

### ISSUE THREAD

**Issue by MLBStream** [b-jesch/skin.estuary.modv2#8]
Hi!
Is it a way to map genres to XML in IPTV EPG? I could do it on the Original Estuary but I can't do it in this MOD. If I choice an XML file nothing change. I could get some color on the EPG but the one that had been modified.

Thanks!

**Comment by b-jesch** [comment]
Please tell me the way to map genres in Estuary (do you mean colored epg?) The EPG-Timeline view in this skin is similar to the timeline view in Estuary.

**Comment by MLBStream** [comment]
I can create a modified XML file or use an existing file that come by default in "userdta/addon_data/pvr.iptvsimple/genres" path, with tags similar to this:

 `<genres>
<genre genreId="0x10">Drama</genre>
</genres>`

I think Estuary Mod doesn't read these XML configuration, I guess that MOD take colored EPG from PNG images in "addons/skin.estuary.modv2/extras/epg-genres"

Btw, yes i meant colored EPG.

**Comment by b-jesch** [comment]
It is indeed possible to switch between specific genre types (from Variables.xml):

```	
<variable name="PVRGenresVar">
		<value condition="Skin.HasSetting(standard_PVRGenres)">$INFO[ListItem.Property(GenreType),windows/pvr/epg-genres/,.png]</value>
		<value>$INFO[ListItem.Genre,special://skin/extras/epg-genres/,.png]</value>
</variable>
```

This settings switches between the views:

![Bildschirmfoto von 2021-06-24 10-17-45](https://user-images.githubusercontent.com/10152384/123228361-aa95d200-d4d5-11eb-8dbe-cbf1dfcc4a27.png)

Maybe this is the solution you are looking for?

**Comment by MLBStream** [comment]
Thanks, that did the job!
