### ISSUE TITLE
Use different font size based on screen size

### ISSUE THREAD

**Issue by Werve** [b-jesch/skin.estuary.modv2#88]
Since I recently used Kodi (19.4) on a relatively small 24" TV at a distance of more than 2 m, I noticed that the smaller writings of the interface are practically unreadable. 
I noticed that some skins (eg Mimic) have different font sets available to try to fix these situations. 
It would therefore be useful to have several font sets to choose from (or just the same but with different sizes for different distance scenarios).

**Comment by b-jesch** [comment]
The used default font is already a font which is easy to read for longer distances. The only solution could be a bigger font size - but different (bigger) size needs a rework for mostly all windows and results in a big bunch of work - even if this should switchable. Not possible for me.

Use a different skin like Estouchy or Mimic.
