### ISSUE TITLE
Can't install due to "The dependency on xbmc.python version 3.0.1 could not be satisfied"

### ISSUE THREAD

**Issue by mYnDstrEAm** [b-jesch/skin.estuary.modv2#89]
When trying to install from the .zip file I get an error message popup and a log entry saying `ERROR <general>: CAddonInstallJob[skin.estuary.modv2]: The dependency on xbmc.python version 3.0.1 could not be satisfied.`. I'm using Kodi 19.1 in Debian11 and tried to install the .zip file from the releases (`skin.estuary.modv2-4.0.2-nexus.1.zip` with sha256sum `78d944d6a919d9bc069a4c02939a71d6ff28e972fc4909d2a5351fb7ead97d88`).

I think other Kodi addons had the same or similar python dependency problems, so the solution can probably already be found there - I think the addon where I had this same error was the [lutris-kodi addon](https://github.com/RobLoach/lutris-kodi-addon).

I tried to install the skin to be able to add items to the left sidebar and for adding streams from a media library to the Movies/Documentaries page as a user recommended the skin [here](https://www.reddit.com/r/kodi/comments/y207mh/comment/is1rx12/?utm_source=reddit&utm_medium=web2x&context=3).

Another thing: to install the skin I noticed I downloaded the file `repository.kodinerds-7.0.1.2.zip` before to install the kodinerds repo (which I didn't do) and the .zip I downloaded back then was 0.4 KiB larger (427.9 KiB) and has sha256sum `b4de45c51d552421b35f16761cc549757ed91509722a2b04de3c75cc9e692f01`, the version I downloaded now has sha256sum `45113ff5baa3c4e11d6b9120a946a4f71f3715c87c42eac63e3afdb1b4eef870` so the file must have been changed in between despite of the exact same filename. I try to avoid installing files that aren't checked against hashsums for security reasons. I don't know why people do this instead of putting things in proper repositories with security mechanisms. These are the kind problems why at least major use-cases should just be supported by default Kodi and not require tinkering. Maybe I'll open an issue there. If you know where to raise this issue, please let me know, I don't think there's a repo for the kodinerds repo on GitHub.

**Comment by b-jesch** [comment]
You can't install a Nexus version of the skin on Matrix (Kodi. 19.x). Also it's recommended to install an addon from repository and not from zip - otherwise you have to manual install all addon dependencies and you'll never receive any updates from the addons. Bad way.

The skin is hosted by the Kodinerds Repo (repo.kodinerds.net). Install the repo addon from there. After doing that you can install the Estuary Mod V2 Matrix with all dependend addon automatically from there.

> I downloaded the file repository.kodinerds-7.0.1.2.zip before to install the kodinerds repo (which I didn't do) and the .zip I downloaded back then was 0.4 KiB larger (427.9 KiB) and has sha256sum b4de45c51d552421b35f16761cc549757ed91509722a2b04de3c75cc9e692f01, the version I downloaded now has sha256sum 45113ff5baa3c4e11d6b9120a946a4f71f3715c87c42eac63e3afdb1b4eef870 so the file must have been changed in between despite of the exact same filename.

Yes. the repository file will updated and new written automatically if an addon of this repo has added, updated or removed by the maintainers.

Regards

**Comment by mYnDstrEAm** [comment]
Okay so I will install from the repo which is what I intended to do first.

However, if the version number stays the same, the file shouldn't change and get smaller. Or did you mean that that zip also changes whenever any of its addon changes? I checked the file and that doesn't seem to be the case but there's only three small files in the zip and I installed the repo now and the skin too.
