### ISSUE TITLE
3.0.9+Matrix freeze my CE 19 rc2 at boot

### ISSUE THREAD

**Issue by GeorgeSands** [b-jesch/skin.estuary.modv2#9]
I use an android Box T95 Max+ 4/32 with Coreelec 19.2Rc2 ng and this addon especially 3.1.2 +Matrix.1 freeze my box at boot and stay with estuary logo for Matrix edition KN freezed for hours

I have to use 3.0.7+Matrix.1 to get working

**Comment by b-jesch** [comment]
Hi,
there is no version 3.1.2+matrix.1 from this Repo. Last version is 3.0.9+matrix as you can see here: https://github.com/b-jesch/skin.estuary.modv2/blob/dab7979be91104f98099106555bf5c7ac06f2c82/addon.xml#L2

Maybe you've override the skin from here with a skin of another repository?

**Comment by GeorgeSands** [comment]
yes sorry my mistake I peak about 3.0.9+Matrix downloaded here https://repo.kodinerds.net/index.php?action=list&scope=all&version=matrix/
it freeze my system on logo "ESTUARY Matrix Edition KN"

**Comment by b-jesch** [comment]
Normally the dependencies would be installed automatically if the skin has been installed directly vom (Kodinerds) repo. So it's a good idea in general to install the repo addon first.

> but I get only icon without text on IPTV channels or Media disk

Maybe this setting: disable in Home menu "show media names with widget names"

**Comment by GeorgeSands** [comment]
Ahhhhhh thank you ! You good 
Thanks and thanks for this mod

**Comment by b-jesch** [comment]
You are welcome.
