### ISSUE TITLE
Nexus skin: Unmatched parentheses in Home.xml

### ISSUE THREAD

**Issue by rainman74** [b-jesch/skin.estuary.modv2#93]
https://github.com/b-jesch/skin.estuary.modv2/blob/Nexus/xml/Home.xml

Wrong: Skin.HasSetting(hide_disabledtimers"
**Right: Skin.HasSetting(hide_disabledtimers)"**

This error is at 2 occurrences!

**Comment by b-jesch** [comment]
Fixed. Thank You.
