### ISSUE TITLE
Blank Dolby vision flag in video osd

### ISSUE THREAD

**Issue by quentinfau** [b-jesch/skin.estuary.modv2#94]
Hello, 

In the library view, the Dolby vision flag appears correctly, but when the media is playing, the flag is blank in the video osd.

Thanks in advance!

**Comment by b-jesch** [comment]
Fixed: https://github.com/b-jesch/skin.estuary.modv2/commit/aface2bfaf88640ed4748d3a6b0c0e324e5e6809
