### ISSUE TITLE
when trailer ends, nothing happens

### ISSUE THREAD

**Issue by C4Wiz** [b-jesch/skin.estuary.modv2#98]
when a trailer ends kodi used to return to the movie wall, not it just sits at the end of the trailer

**Comment by b-jesch** [comment]
Yes, this is the default behaviour when using 'Play Trailer' from context menu. If you play a trailer via button in video info, this window still stays open when trailer has ended.

**Comment by C4Wiz** [comment]
i am playing trailers from trailer button in video info, and trailer stays open

**Comment by b-jesch** [comment]
I don't have this behaviour. Trailer is closing on end and the video info window turns back - independent if the trailer is playing fullscreen or windowed mode.

**Comment by C4Wiz** [comment]
> I don't have this behaviour. Trailer is closing on end and the video info window turns back - independent if the trailer is playing fullscreen or windowed mode. Do you have tried another movie?

i have tried several

where is the section in the xml's for the behavior? maybe i missed a commit

**Comment by C4Wiz** [comment]
fixed on my end, sorry
